name: internet_file
description: A internet file getter (also optional downloader) that works in all platforms
repository: https://github.com/ScerIO/packages.dart/tree/master/packages/internet_file
issue_tracker: ^1.2.2
version: 1.2.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  http: ^1.2.2
  path: ^1.9.0
  universal_file: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
